server:
  port: 1010
 
spring:  mail:    host: smtp.gmail.com
    port: 587
    username: razkumar4528@gmail.com
    password: raju.3019
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        
        
